---
- name: Basic filters
  hosts: localhost
  gather_facts: no


  vars:
    jarlist: [1,1,1,1,1,5]
    repeatlist: [1,2,2,2,4,4,4,4,9,9,9,9]
    repaat2list: [5,5,5,5,5,6]
    complexlist: [6,7,8,[9,10,22],87]

  tasks:
  - name: min filter
    debug:
      msg: "show the lowest '{{ jarlist | min }}'"


  - name: display complex without filter
    debug:
      msg: "show the complex list  '{{ complexlist  }}'   "

  - name: flatten filter
    debug:
      msg: "show the flatten  complex list  '{{ complexlist | flatten  }}'   "
